# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MosyleFamily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MosyleFamily

  pod 'Alamofire', '~> 4.2.0'
  pod 'Kingfisher'


  target 'MosyleFamilyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MosyleFamilyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
